services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=jdbc:postgresql://localhost:5432/postgres'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
