spring:
  datasource:
    password: 1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: false
    hibernate:
        ddl-auto: update
    show-sql: true
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: never