spring:
  datasource:
    password: 1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    defer-datasource-initialization: false
    hibernate:
        ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: never